### ISSUE TITLE
Bug addOrRemoveLabels?

### ISSUE THREAD

**Issue by loic-hamdi** [wppconnect-team/wa-js#1272]
Hi guys,

Thanks for the great work on this package.

I am trying to use [addOrRemoveLabels](https://wppconnect.io/wa-js/functions/labels.addOrRemoveLabels.html) but I always face this error message:

```ReferenceError: add is not defined```

Could you please confirm that the example actually works for you?

```js
await WPP.labels.addOrRemoveLabels(
  ['[number]@c.us','[number]@c.us'],
  [{labelId:'76', type:'add'},{labelId:'75', type:'remove'}]
)
```

**Comment by icleitoncosta** [comment]
Hello, I conducted tests using the latest version, and everything is going well. Following your example exactly might result in an error since labels with IDs 76 and 75 don't actually exist.

Prior to that, use WPP.labels.getAllLabels() to get all labels, and then make the calls according to the correct labelId.

I'll close the issue, but if you need anything, just let me know. Please feel free to reach out.
