### ISSUE TITLE
ChatList with unread messages

### ISSUE THREAD

**Issue by daviladanielc** [wppconnect-team/wa-js#730]
## Description

When I use the Chat List({only With Unread Message: true}) function, it returns property isNewMsg: True.
if I disconnect and reconnect, keeping the message unread. And run ChatList, isNewMsg property does not appear, even unread message notification appearing
I made a video showing the tests.

## Environment

- **WhatsApp version:** 2.2242.6 e 2.2241.6
- **WA-JS version(s):** v2.14.1
- **Browser:** Chromium 101
- **OS:** Windows 10
- **MultiDevice:** yes

## Steps to Reproduce

Vídeo: 

https://user-images.githubusercontent.com/71415962/199616868-627d8748-b515-4025-a0c4-92639d65685b.mp4

## Your Code

```
const chatteste = await WPP.chat.list({onlyWithUnreadMessage: true});
```

**Comment by edgardmessias** [comment]
@daviladanielc, about `isNewMsg`, this is an expected behavior, but I believe that you are getting confused about the subjects. About messages, I stronly recomend you to see this function: `WPP.chat.getMessages` https://wppconnect.io/wa-js/functions/chat.getMessages.html

pt-BR: Sobre o `isNewMsg` é um comportamento esperado, mas acredito que você está misturando os pontos. Sobre as mensagens, recomendo olhar essa função: `WPP.chat.getMessages` https://wppconnect.io/wa-js/functions/chat.getMessages.html
